unit TestBufStreamReader;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, CustomTestCase, System.Classes, BufStreamReader, System.SysUtils, BufStream;

type
  // Test methods for class BufferedStreamReader

  TestBufferedStreamReaderBase = class(TCustomTestCase)
  strict private
    FLine1: string;
    FLine2: string;
    FLine3: string;
    FBufferedStreamReader: BufferedStreamReader;
  protected
    procedure CreateTestStreamReader(const BufferSize: integer);
  public
    procedure TearDown; override;
  published
    procedure TestReadChars;
    procedure TestReadLine;
    procedure TestReadUntil;
    procedure TestReadUntil1;
    procedure TestReadToEnd;
  end;

  TestBufferedStreamReaderSmallBuffer = class(TestBufferedStreamReaderBase)
  public
    procedure SetUp; override;
  end;

  TestBufferedStreamReaderLargeBuffer = class(TestBufferedStreamReaderBase)
  public
    procedure SetUp; override;
  end;

implementation

procedure TestBufferedStreamReaderBase.CreateTestStreamReader(const BufferSize: integer);
var
  data: TBytes;
  bs: TBytesStream;
  src: BufferedStream;
begin
  FLine1 := 'This is a test';
  FLine2 := 'Это тест';
  FLine3 := '0123456789';

  data := TEncoding.UTF8.GetBytes(
    FLine1 + #13#10 +
    FLine2 + #13#10 +
    FLine3);
  bs := TBytesStream.Create(data);
  src := BufferedStream.Create(bs, [BufferedStreamOwnsSource], BufferSize);
  FBufferedStreamReader := BufferedStreamReader.Create(src, TEncoding.UTF8, [BufferedStreamReaderOwnsSource]);
end;

procedure TestBufferedStreamReaderBase.TearDown;
begin
  FBufferedStreamReader.Free;
  FBufferedStreamReader := nil;
end;

procedure TestBufferedStreamReaderBase.TestReadChars;
var
  ReturnValue: TCharArray;
  CharCount: Integer;
begin
  CharCount := 1;
  ReturnValue := FBufferedStreamReader.ReadChars(CharCount);
  CheckEquals(FLine1.ToCharArray(0, CharCount), ReturnValue, 'ReadChars failed on first line');

  FBufferedStreamReader.ReadLine;

  CharCount := 2;
  ReturnValue := FBufferedStreamReader.ReadChars(CharCount);
  CheckEquals(FLine2.ToCharArray(0, CharCount), ReturnValue, 'ReadChars failed on second line');

  FBufferedStreamReader.ReadLine;

  CharCount := 3;
  ReturnValue := FBufferedStreamReader.ReadChars(CharCount);
  CheckEquals(FLine3.ToCharArray(0, CharCount), ReturnValue, 'ReadChars failed on third line');
end;

procedure TestBufferedStreamReaderBase.TestReadLine;
var
  ReturnValue: string;
begin
  ReturnValue := FBufferedStreamReader.ReadLine;
  CheckEquals(FLine1, ReturnValue, 'ReadLine failed on first line');
  CheckFalse(FBufferedStreamReader.EndOfStream, 'ReadLine prematurely signaled end of stream on first line');

  ReturnValue := FBufferedStreamReader.ReadLine;
  CheckEquals(FLine2, ReturnValue, 'ReadLine failed on second line');
  CheckFalse(FBufferedStreamReader.EndOfStream, 'ReadLine prematurely signaled end of stream on second line');

  ReturnValue := FBufferedStreamReader.ReadLine;
  CheckEquals(FLine3, ReturnValue, 'ReadLine failed on third line');
  CheckTrue(FBufferedStreamReader.EndOfStream, 'ReadLine failed to signaled end of stream on third line');
end;

procedure TestBufferedStreamReaderBase.TestReadUntil;
var
  ReturnValue: string;
  Delimiter: Byte;
begin
  exit;

  // TODO: Setup method call parameters
  ReturnValue := FBufferedStreamReader.ReadUntil(Delimiter);
  // TODO: Validate method results
end;

procedure TestBufferedStreamReaderBase.TestReadUntil1;
var
  ReturnValue: string;
  Delimiter: string;
begin
  exit;

  // TODO: Setup method call parameters
  ReturnValue := FBufferedStreamReader.ReadUntil(Delimiter);
  // TODO: Validate method results
end;

procedure TestBufferedStreamReaderBase.TestReadToEnd;
var
  ReturnValue: string;
begin
  FBufferedStreamReader.ReadLine;

  ReturnValue := FBufferedStreamReader.ReadToEnd;

  CheckEquals(FLine2 + #13#10 + FLine3, ReturnValue, 'ReadToEnd failed');
end;

{ TestBufferedStreamReaderSmallBuffer }

procedure TestBufferedStreamReaderSmallBuffer.SetUp;
begin
  CreateTestStreamReader(3);
end;

{ TestBufferedStreamReaderLargeBuffer }

procedure TestBufferedStreamReaderLargeBuffer.SetUp;
begin
  CreateTestStreamReader(4096);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestBufferedStreamReaderSmallBuffer.Suite);
  RegisterTest(TestBufferedStreamReaderLargeBuffer.Suite);
end.

